package com.example.composeexplorer.activities.functions.livetemplates

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier

// The code snippets below are generated by the live template to enhance workflow efficiency.

@Composable
fun LiveTemplateTest() {

    Column (
        // mod = Will create a modifier:
        modifier = Modifier.fillMaxSize() ,


        // varr = will create a verticalArrangement:
        verticalArrangement = Arrangement.Center,


        // harr = will create a horizontalAlignment:
        horizontalAlignment = Alignment.CenterHorizontally
        
    ){

    }

}